#ifndef SNAKE_VERIFIER_H
#define SNAKE_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef SNAKE_READER_H
#include "snake_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int Snake_Message_Command_verify_table(flatcc_table_verifier_descriptor_t *td);

static int Snake_Message_Command_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* direction */)) return ret;
    return flatcc_verify_ok;
}

static inline int Snake_Message_Command_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Snake_Message_Command_identifier, &Snake_Message_Command_verify_table);
}

static inline int Snake_Message_Command_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Snake_Message_Command_type_identifier, &Snake_Message_Command_verify_table);
}

static inline int Snake_Message_Command_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &Snake_Message_Command_verify_table);
}

static inline int Snake_Message_Command_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &Snake_Message_Command_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SNAKE_VERIFIER_H */
